language: ruby
rvm: 2.0.0
notifications:
  email: false
bundler_args: --binstubs
env:
  global:
    - GIT_COMMITTER_NAME="Keiji Matsuzaki"
    - GIT_COMMITTER_EMAIL=futoase@gmail.com
    - GIT_AUTHOR_NAME="Keiji Matsuzaki"
    - GIT_AUTHOR_EMAIL=futoase@gmail.com
    - secure: "KwWEFG5q0King8CwkFv8tstAuwFALzJqgdRxeS5DVMnGsIhSKzJwOrDK8rkdIK9+07xgHbZuLwwzWT4VVwHWORPxbt6kUNfVJA32LeZUoDEll6RpKpdmwWhKo1KMvMqmZBdTTvmjPGG8DeRJLrvvPTUJLh16h2uhEfQQhAbGnbU="
before_script:
  - git clone --quiet https://github.com/futoase/futoase.github.io.git build
  - pushd build
  - git checkout -b gh-pages
  - popd
script: 
  - bundle exec middleman build
after_success:
  - cd build
  - git add -A
  - git commit -m 'Update!'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push -f --quiet https://$GH_TOKEN@github.com/futoase/futoase.github.io.git gh-pages 2> /dev/null'
